# Generated by Django 2.2.5 on 2019-09-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190928_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superHost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
